In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('data/clean_data.csv')

In [3]:
data.head()

,UNIQUEID,DISBURSED_AMOUNT,ASSET_COST,LTV,BRANCH_ID,SUPPLIER_ID,MANUFACTURER_ID,CURRENT_PINCODE_ID,EMPLOYMENT_TYPE,DISBURSAL_DATE,...,SEC_ACTIVE_ACCTS,SEC_OVERDUE_ACCTS,NEW_ACCTS_IN_LAST_SIX_MONTHS,DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS,AVERAGE_ACCT_AGE,CREDIT_HISTORY_LENGTH,NO_OF_INQUIRIES,LOAN_DEFAULT,APPLICATES_AGE,DISBURSAL_AGE
0,420825,0.439324,0.230606,0.875911,67,22807,45,1441,1,2018-03-08,...,0,0,0,0,0.00,0.0,0,0,38.0,4.0
1,417566,0.490280,0.289956,0.877732,67,22807,45,1497,2,2018-01-08,...,0,0,0,0,0.00,0.0,0,0,37.0,4.0
2,539055,0.473295,0.268703,0.849499,67,22807,45,1495,2,2018-09-26,...,0,0,0,0,0.00,0.0,1,1,45.0,4.0
3,518279,0.513588,0.300784,0.878415,67,22807,45,1501,2,2018-09-19,...,0,0,0,0,1.75,2.0,0,0,32.0,4.0
4,529269,0.359510,0.292764,0.576958,67,22807,45,1502,1,2018-09-23,...,0,0,0,0,0.00,0.0,0,0,34.0,4.0

In [7]:
data['NEW_ACCTS_IN_LAST_SIX_MONTHS'].unique()

array([ 0,  1,  2,  3,  4,  5,  7, 20,  8])

### feature selection